//ADMIN TOOLS
ADMINTOOLS_SCRIPT = true;
//Regen Blood
REGENBLOOD_SCRIPT = true;
//DZAI
DZAI_SCRIPT = true;
//WAI
WAI_SCRIPT = true;
//DZMS
DZMS_SCRIPT = true;
//ESS
ESS_SCRIPT = true;
//WATERMARK/LOGO
LOGO_SCRIPT = true;
//DUST
DUST_SCRIPT = true;
//SNOW
SNOW_SCRIPT = true;
//FOG
FOG_SCRIPT = true;


//DO NOT EDIT THIS! - ITS USED TO HELP WITH SUPPORT REQUESTS!
REPACKMOD = "0.17 - Long Time Coming"; 
BUILDNUMBER = "10";