//ADMIN TOOLS
ADMINTOOLS_SCRIPT = true;
//Regen Blood
REGENBLOOD_SCRIPT = true;


//DO NOT EDIT THIS! - ITS USED TO HELP WITH SUPPORT REQUESTS!
REPACKMOD = "0.17 - Long Time Coming"; 
BUILDNUMBER = "0.03";