//WELCOME CREDITS
WELCOME_MESSAGES = true;
//ADMIN TOOLS
ADMINTOOLS_SCRIPT = true;



//DO NOT EDIT THIS! - ITS USED TO HELP WITH SUPPORT REQUESTS!
REPACKMOD = "0.17 - Long Time Coming"; 
BUILDNUMBER = "1";